# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Exercise.create(name: "Walking, less than 2 mph", met: 2.0 )
Exercise.create(name: "Walking, 3 mph", met: 3.5)
Exercise.create(name: "Walking, 3.5 mph", met: 4.0)
Exercise.create(name: "Walking, 4 mph", met: 4.5)
Exercise.create(name: "Stairmaster", met: 9.0)
Exercise.create(name: "Light Yoga", met: 2.5)
Exercise.create(name: "Golf", met: 4.3 )
Exercise.create(name: "Lawn Mowing", met: 5.0 )
Exercise.create(name: "Swimming, leisurely pace", met: 6.0 )
Exercise.create(name: "Bicycling, casual, less than 10 mph", met: 4.0 )
Exercise.create(name: "Bicycling, 10 mph", met: 6.0 )
Exercise.create(name: "Bicycling, 12.5 mph", met: 7.1 )
Exercise.create(name: "Bicycling, 15.5 mph", met: 8.4 )
Exercise.create(name: "Bicycling, 20 mph", met: 9.9 )
Exercise.create(name: "Circuit Training", met: 8.0)
Exercise.create(name: "Tennis, singles", met: 7.0)
Exercise.create(name: "Tennis, doubles", met: 4.5)
Exercise.create(name: "Shoveling, digging ditches", met: 8.5)
Exercise.create(name: "Competetive Soccer", met: 10.0 )
Exercise.create(name: "Gardening", met: 2.0)
Exercise.create(name: "Climbing stairs", met: 4.0 )
Exercise.create(name: "Dancing, ballet or modern", met: 4.8 )
Exercise.create(name: "Hiking, strenuous", met: 6.5)
Exercise.create(name: "Rowing or Kayaking", met: 7.0 )
Exercise.create(name: "Skiing", met: 7.0 )
Exercise.create(name: "Running, 5 mph", met: 8.0)
Exercise.create(name: "Running, 6 mph", met: 10.0)
Exercise.create(name: "Running, 7 mph", met: 11.5)
Exercise.create(name: "Running, 8 mph", met: 13.5)
Exercise.create(name: "Running, 9 mph", met: 15.0)
Exercise.create(name: "Running, 10 mph", met: 16.0)
Exercise.create(name: "Badminton, competetive", met: 6.0 )
Exercise.create(name: "Badminton, singles", met: 4.5 )
Exercise.create(name: "Baseball", met: 5.5 )
Exercise.create(name: "Basketball", met: 11.1 )
Exercise.create(name: "Boxing", met: 13.4)
Exercise.create(name: "Cricket", met: 6.1 )
Exercise.create(name: "Figure Skating", met: 12.9 )
Exercise.create(name: "Gymnastics", met: 7.0 )
Exercise.create(name: "Home calisthenics", met: 4.0 )
Exercise.create(name: "Jump Rope, 66/min", met: 9.8 )
Exercise.create(name: "Jump Rope, 84/min", met: 10.5 )
Exercise.create(name: "Jump Rope, 100/min", met: 11.0 )
Exercise.create(name: "Jump Rope, 120/min", met: 11.4 )
Exercise.create(name: "Jump Rope, 135/min", met: 12.0 )
Exercise.create(name: "Weight training, hypertrophy", met: 12.1 )
Exercise.create(name: "Weight training, strength", met: 10.9 )